In [1]:
import pandas as pd
import numpy as np

# Create a mock spreadsheet layout resembling a StatsBomb data split
data_check = {
    'match_id': [3788741, 3788741],
    'player': ['Enzo Fernández', 'Moises Caicedo'],
    'event_type': ['Pass', 'Pass']
}
df = pd.DataFrame(data_check)

print("Pandas version:", pd.__version__)
print("\nYour first football dataframe loaded successfully:")
display(df)

Pandas version: 3.0.3

Your first football dataframe loaded successfully:

   match_id          player event_type
0   3788741  Enzo Fernández       Pass
1   3788741  Moises Caicedo       Pass

In [2]:
# Filter the dataframe to only show passes made by Enzo Fernández
enzo_passes = df[df['player'] == 'Enzo Fernández']

print("Filtered Dataframe:")
display(enzo_passes)

Filtered Dataframe:

   match_id          player event_type
0   3788741  Enzo Fernández       Pass

In [3]:
import pandas as pd

revision_df = pd.DataFrame({
    'minute': [4, 14, 22, 45, 89],
    'player': ['Enzo Fernández', 'Moises Caicedo', 'Enzo Fernández', 'Cole Palmer', 'Enzo Fernández'],
    'event_type': ['Pass', 'Tackle', 'Pass', 'Shot', 'Pass'],
    'under_pressure': [0, 1, 1, 0, 1]
})

In [4]:
revision_df.head

<bound method NDFrame.head of    minute          player event_type  under_pressure
0       4  Enzo Fernández       Pass               0
1      14  Moises Caicedo     Tackle               1
2      22  Enzo Fernández       Pass               1
3      45     Cole Palmer       Shot               0
4      89  Enzo Fernández       Pass               1>

In [5]:
enzo_late_events = revision_df[(revision_df['player'] == 'Enzo Fernández') & (revision_df['minute'] > 10)]
display(enzo_late_events)

   minute          player event_type  under_pressure
2      22  Enzo Fernández       Pass               1
4      89  Enzo Fernández       Pass               1

In [6]:
high_risk_events = revision_df[(revision_df['under_pressure'] == 1) | (revision_df['minute'] > 80)]
high_risk_events

   minute          player event_type  under_pressure
1      14  Moises Caicedo     Tackle               1
2      22  Enzo Fernández       Pass               1
4      89  Enzo Fernández       Pass               1

In [7]:
early_defensive_actions = revision_df[(revision_df['event_type'] != 'Pass') & (revision_df['minute'] < 15)]
early_defensive_actions

   minute          player event_type  under_pressure
1      14  Moises Caicedo     Tackle               1

In [8]:
caicedo_under_pressure = revision_df[(revision_df['player'] == 'Moises Caicedo') & (revision_df['under_pressure'] == 1)]
caicedo_under_pressure

   minute          player event_type  under_pressure
1      14  Moises Caicedo     Tackle               1

In [9]:
!pip install requests

Requirement already satisfied: requests in C:\Users\xaral\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.34.2)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\xaral\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\xaral\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\xaral\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\xaral\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests) (2026.6.17)

In [10]:
import pandas as pd
import requests

# URL for a single match event stream from StatsBomb open data 
# (Champions League Final: Barcelona vs Juventus)
match_url = "https://raw.githubusercontent.com/statsbomb/open-data/master/data/events/3754058.json"

# Download the raw nested JSON data stream
raw_events = requests.get(match_url).json()

# Convert the top-level array into a base dataframe
df_raw = pd.DataFrame(raw_events)

print("Raw Dataframe Dimensions:", df_raw.shape)
print("\nFirst 3 columns of the raw file:")
print(df_raw[['id', 'type', 'player']].head(5))

Raw Dataframe Dimensions: (3576, 35)

First 3 columns of the raw file:
                                     id                               type  \
0  9153e9f4-f69c-4e04-8f64-505592e212cd  {'id': 35, 'name': 'Starting XI'}
1  3fbcf4e7-94d1-485a-be85-fd26a6af0318  {'id': 35, 'name': 'Starting XI'}
2  06a9a4dc-d9c9-40f6-bd89-437ba7fe682d   {'id': 18, 'name': 'Half Start'}
3  100362ee-9311-4187-bd8a-0201d9db2565   {'id': 18, 'name': 'Half Start'}
4  2ca23eea-a984-47e4-8243-8f00880ad1c9         {'id': 30, 'name': 'Pass'}

                                player
0                                  NaN
1                                  NaN
2                                  NaN
3                                  NaN
4  {'id': 3343, 'name': 'Dan Gosling'}

In [11]:
df_raw['pass'].head

<bound method NDFrame.head of 0                                                     NaN
1                                                     NaN
2                                                     NaN
3                                                     NaN
4       {'recipient': {'id': 3346, 'name': 'Joshua Kin...
                              ...
3571                                                  NaN
3572    {'recipient': {'id': 3814, 'name': 'Riyad Mahr...
3573                                                  NaN
3574                                                  NaN
3575                                                  NaN
Name: pass, Length: 3576, dtype: object>

In [12]:
df_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 3576 entries, 0 to 3575
Data columns (total 35 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               3576 non-null   str
 1   index            3576 non-null   int64
 2   period           3576 non-null   int64
 3   timestamp        3576 non-null   str
 4   minute           3576 non-null   int64
 5   second           3576 non-null   int64
 6   type             3576 non-null   object
 7   possession       3576 non-null   int64
 8   possession_team  3576 non-null   object
 9   play_pattern     3576 non-null   object
 10  team             3576 non-null   object
 11  duration         2652 non-null   float64
 12  tactics          3 non-null      object
 13  related_events   3417 non-null   object
 14  player           3565 non-null   object
 15  position         3565 non-null   object
 16  location         3555 non-null   object
 17  pass             1002 non-null   object
 18  carry            742 non-null    object
 19  under_pressure   865 non-null    object
 20  duel             83 non-null     object
 21  ball_receipt     156 non-null    object
 22  counterpress     121 non-null    object
 23  shot             27 non-null     object
 24  goalkeeper       35 non-null     object
 25  clearance        59 non-null     object
 26  off_camera       64 non-null     object
 27  out              35 non-null     object
 28  dribble          31 non-null     object
 29  interception     25 non-null     object
 30  foul_committed   10 non-null     object
 31  foul_won         8 non-null      object
 32  ball_recovery    7 non-null      object
 33  substitution     5 non-null      object
 34  miscontrol       1 non-null      object
dtypes: float64(1), int64(5), object(27), str(2)
memory usage: 977.9+ KB

In [13]:
df_raw['type'].head

<bound method NDFrame.head of 0         {'id': 35, 'name': 'Starting XI'}
1         {'id': 35, 'name': 'Starting XI'}
2          {'id': 18, 'name': 'Half Start'}
3          {'id': 18, 'name': 'Half Start'}
4                {'id': 30, 'name': 'Pass'}
                       ...
3571            {'id': 43, 'name': 'Carry'}
3572             {'id': 30, 'name': 'Pass'}
3573    {'id': 42, 'name': 'Ball Receipt*'}
3574         {'id': 34, 'name': 'Half End'}
3575         {'id': 34, 'name': 'Half End'}
Name: type, Length: 3576, dtype: object>

In [14]:
df_raw['event_type'] = df_raw['type'].apply(lambda x: x.get('name') if isinstance(x, dict) else None)

In [15]:
df_raw['event_type'].head

<bound method NDFrame.head of 0         Starting XI
1         Starting XI
2          Half Start
3          Half Start
4                Pass
            ...
3571            Carry
3572             Pass
3573    Ball Receipt*
3574         Half End
3575         Half End
Name: event_type, Length: 3576, dtype: str>

In [16]:
df_pass = df_raw[df_raw['event_type'] == 'Pass']
df_pass.info()

<class 'pandas.DataFrame'>
Index: 1002 entries, 4 to 3572
Data columns (total 36 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1002 non-null   str
 1   index            1002 non-null   int64
 2   period           1002 non-null   int64
 3   timestamp        1002 non-null   str
 4   minute           1002 non-null   int64
 5   second           1002 non-null   int64
 6   type             1002 non-null   object
 7   possession       1002 non-null   int64
 8   possession_team  1002 non-null   object
 9   play_pattern     1002 non-null   object
 10  team             1002 non-null   object
 11  duration         1002 non-null   float64
 12  tactics          0 non-null      object
 13  related_events   993 non-null    object
 14  player           1002 non-null   object
 15  position         1002 non-null   object
 16  location         1002 non-null   object
 17  pass             1002 non-null   object
 18  carry            0 non-null      object
 19  under_pressure   215 non-null    object
 20  duel             0 non-null      object
 21  ball_receipt     0 non-null      object
 22  counterpress     3 non-null      object
 23  shot             0 non-null      object
 24  goalkeeper       0 non-null      object
 25  clearance        0 non-null      object
 26  off_camera       59 non-null     object
 27  out              1 non-null      object
 28  dribble          0 non-null      object
 29  interception     0 non-null      object
 30  foul_committed   0 non-null      object
 31  foul_won         0 non-null      object
 32  ball_recovery    0 non-null      object
 33  substitution     0 non-null      object
 34  miscontrol       0 non-null      object
 35  event_type       1002 non-null   str
dtypes: float64(1), int64(5), object(27), str(3)
memory usage: 289.6+ KB

In [17]:
df_pass.iloc[0]

id                              2ca23eea-a984-47e4-8243-8f00880ad1c9
index                                                              5
period                                                             1
timestamp                                               00:00:01.753
minute                                                             0
second                                                             1
type                                      {'id': 30, 'name': 'Pass'}
possession                                                         2
possession_team                {'id': 28, 'name': 'AFC Bournemouth'}
play_pattern                      {'id': 9, 'name': 'From Kick Off'}
team                           {'id': 28, 'name': 'AFC Bournemouth'}
duration                                                    0.308263
tactics                                                          NaN
related_events                [1f98c89e-2326-4200-8c12-a987fdbbaf2e]
player                           {'id': 3343, 'name': 'Dan Gosling'}
position                 {'id': 13, 'name': 'Right Center Midfield'}
location                                                [61.0, 40.1]
pass               {'recipient': {'id': 3346, 'name': 'Joshua Kin...
carry                                                            NaN
under_pressure                                                   NaN
duel                                                             NaN
ball_receipt                                                     NaN
counterpress                                                     NaN
shot                                                             NaN
goalkeeper                                                       NaN
clearance                                                        NaN
off_camera                                                       NaN
out                                                              NaN
dribble                                                          NaN
interception                                                     NaN
foul_committed                                                   NaN
foul_won                                                         NaN
ball_recovery                                                    NaN
substitution                                                     NaN
miscontrol                                                       NaN
event_type                                                      Pass
Name: 4, dtype: object

In [18]:
df_pass['length'] = df_pass['pass'].apply(lambda x: x.get('length') if isinstance(x, dict) else None)
df_pass['length'].head()

4      3.551056
7     12.544720
9     35.966790
12    19.345800
15    15.890248
Name: length, dtype: float64

In [19]:
df_pass['angle'] = df_pass['pass'].apply(lambda x: x.get('angle') if isinstance(x, dict) else None)
df_pass['angle'].head()

4     1.740575
7    -2.989549
9     1.867047
12   -2.120081
15    1.064920
Name: angle, dtype: float64

In [20]:
df_pass['height'] = df_pass['pass'].apply(lambda x: x.get('height',{}).get('name') if isinstance(x, dict) else None)
df_pass['height'].head()

4     Ground Pass
7     Ground Pass
9     Ground Pass
12    Ground Pass
15    Ground Pass
Name: height, dtype: str

In [21]:
print(df_pass['pass'].iloc[101])

{'recipient': {'id': 3346, 'name': 'Joshua King'}, 'length': 25.632206, 'angle': -0.10160965, 'height': {'id': 1, 'name': 'Ground Pass'}, 'end_location': [69.8, 26.7], 'body_part': {'id': 38, 'name': 'Left Foot'}, 'outcome': {'id': 9, 'name': 'Incomplete'}}

In [22]:
df_pass['outcome'] = df_pass['pass'].apply(lambda x: x.get('outcome',{}).get('name') if isinstance(x, dict) else None)
df_pass['outcome'].head()

4     NaN
7     NaN
9     NaN
12    NaN
15    NaN
Name: outcome, dtype: str

In [23]:
df_pass['outcome'] = df_pass['outcome'].fillna('Complete')
df_pass['outcome'].head()

4     Complete
7     Complete
9     Complete
12    Complete
15    Complete
Name: outcome, dtype: str

In [24]:
df_pass['target'] = (df_pass['outcome'] == 'Complete').astype(int)
df_pass['target'].head()

4     1
7     1
9     1
12    1
15    1
Name: target, dtype: int64

In [25]:
print(df_pass['target'].value_counts(normalize=True))

target
1    0.766467
0    0.233533
Name: proportion, dtype: float64

In [26]:
df_pass['under_pressure'] = df_pass['under_pressure'].fillna(0).astype(int)
df_pass['under_pressure'].head()

4     0
7     0
9     0
12    0
15    0
Name: under_pressure, dtype: int64

In [27]:
print(df_pass['under_pressure'].value_counts(normalize=True))

under_pressure
0    0.785429
1    0.214571
Name: proportion, dtype: float64

In [28]:
print(df_pass.groupby('under_pressure')['target'].value_counts(normalize=True))

under_pressure  target
0               1         0.773825
                0         0.226175
1               1         0.739535
                0         0.260465
Name: proportion, dtype: float64

In [29]:
df_pass.columns

Index(['id', 'index', 'period', 'timestamp', 'minute', 'second', 'type',
       'possession', 'possession_team', 'play_pattern', 'team', 'duration',
       'tactics', 'related_events', 'player', 'position', 'location', 'pass',
       'carry', 'under_pressure', 'duel', 'ball_receipt', 'counterpress',
       'shot', 'goalkeeper', 'clearance', 'off_camera', 'out', 'dribble',
       'interception', 'foul_committed', 'foul_won', 'ball_recovery',
       'substitution', 'miscontrol', 'event_type', 'length', 'angle', 'height',
       'outcome', 'target'],
      dtype='str')

In [30]:
df_pass['pass'].iloc[0]

{'recipient': {'id': 3346, 'name': 'Joshua King'},
 'length': 3.5510561,
 'angle': 1.7405746,
 'height': {'id': 1, 'name': 'Ground Pass'},
 'end_location': [60.4, 43.6],
 'type': {'id': 65, 'name': 'Kick Off'},
 'body_part': {'id': 40, 'name': 'Right Foot'}}

In [31]:
df_pass['pass_receiver'] = df_pass['pass'].apply(lambda x: x.get('recipient', {}).get('name') if isinstance(x, dict) else None)
df_pass['pass_receiver'].head()

4       Joshua King
7     Andrew Surman
9        Adam Smith
12    Simon Francis
15       Adam Smith
Name: pass_receiver, dtype: str

In [32]:
# Install the library inside your environment
!pip install statsbombpy

# Import the structural loaders
from statsbombpy import sb

# 1. View all available leagues and their IDs instantly
df_leagues = sb.competitions()
display(df_leagues.head())

# 2. View all matches for a specific league and season
# (e.g., Competition 16 is Champions League)

# 3. Pull the entire flattened event table for a specific match directly
df_events = sb.events(match_id=3754058)

Requirement already satisfied: statsbombpy in C:\Users\xaral\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.20.0)
Requirement already satisfied: pandas in C:\Users\xaral\AppData\Local\Programs\Python\Python313\Lib\site-packages (from statsbombpy) (3.0.3)
Requirement already satisfied: requests in C:\Users\xaral\AppData\Local\Programs\Python\Python313\Lib\site-packages (from statsbombpy) (2.34.2)
Requirement already satisfied: requests-cache in C:\Users\xaral\AppData\Local\Programs\Python\Python313\Lib\site-packages (from statsbombpy) (1.3.2)
Requirement already satisfied: inflect in C:\Users\xaral\AppData\Local\Programs\Python\Python313\Lib\site-packages (from statsbombpy) (7.5.0)
Requirement already satisfied: joblib in C:\Users\xaral\AppData\Local\Programs\Python\Python313\Lib\site-packages (from statsbombpy) (1.5.3)
Requirement already satisfied: more_itertools>=8.5.0 in C:\Users\xaral\AppData\Local\Programs\Python\Python313\Lib\site-packages (from inflect->statsbombpy) (11.1.0)
Requirement already satisfied: typeguard>=4.0.1 in C:\Users\xaral\AppData\Local\Programs\Python\Python313\Lib\site-packages (from inflect->statsbombpy) (4.5.2)
Requirement already satisfied: typing_extensions>=4.14.0 in C:\Users\xaral\AppData\Roaming\Python\Python313\site-packages (from typeguard>=4.0.1->inflect->statsbombpy) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\xaral\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas->statsbombpy) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\xaral\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas->statsbombpy) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\xaral\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas->statsbombpy) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\xaral\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas->statsbombpy) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\xaral\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->statsbombpy) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\xaral\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->statsbombpy) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\xaral\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->statsbombpy) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\xaral\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->statsbombpy) (2026.6.17)
Requirement already satisfied: attrs>=21.2 in C:\Users\xaral\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests-cache->statsbombpy) (26.1.0)
Requirement already satisfied: cattrs>=22.2 in C:\Users\xaral\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests-cache->statsbombpy) (26.1.0)
Requirement already satisfied: platformdirs>=2.5 in C:\Users\xaral\AppData\Roaming\Python\Python313\site-packages (from requests-cache->statsbombpy) (4.10.0)
Requirement already satisfied: url-normalize>=2.0 in C:\Users\xaral\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests-cache->statsbombpy) (3.0.0)

c:\Users\xaral\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-11-15T23:17:41.827093,2025-11-15T23:17:41.827093,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,NaN,NaN,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2026-05-12T21:18:08.827431,2026-05-02T02:07:18.902396,2026-05-02T02:07:18.902396,2026-05-12T21:18:08.827431
3,16,4,Europe,Champions League,male,False,False,2018/2019,2026-05-15T15:54:04.598614,2021-06-13T16:17:31.694,NaN,2026-05-15T15:54:04.598614
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,NaN,2024-02-13T02:35:28.134882

c:\Users\xaral\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [33]:
df_matches = sb.matches(competition_id=9, season_id=281)
display(df_matches[['match_id', 'home_team', 'away_team', 'match_date']])

    match_id                 home_team                 away_team  match_date
0    3895292              Union Berlin          Bayer Leverkusen  2024-04-06
1    3895320          Bayer Leverkusen             VfB Stuttgart  2024-04-27
2    3895158          Bayer Leverkusen         Borussia Dortmund  2023-12-03
3    3895107          Bayer Leverkusen                   FC Köln  2023-10-08
4    3895340                    Bochum          Bayer Leverkusen  2024-05-12
5    3895286          Bayer Leverkusen                Hoffenheim  2024-03-30
6    3895302          Bayer Leverkusen             Werder Bremen  2024-04-14
7    3895333       Eintracht Frankfurt          Bayer Leverkusen  2024-05-05
8    3895348          Bayer Leverkusen                  Augsburg  2024-05-18
9    3895220              Darmstadt 98          Bayer Leverkusen  2024-02-03
10   3895250          Bayer Leverkusen              FSV Mainz 05  2024-02-23
11   3895266          Bayer Leverkusen                 Wolfsburg  2024-03-10
12   3895275                  Freiburg          Bayer Leverkusen  2024-03-17
13   3895180          Bayer Leverkusen       Eintracht Frankfurt  2023-12-17
14   3895134                Hoffenheim          Bayer Leverkusen  2023-11-04
15   3895121          Bayer Leverkusen                  Freiburg  2023-10-29
16   3895074             Bayern Munich          Bayer Leverkusen  2023-09-15
17   3895139          Bayer Leverkusen              Union Berlin  2023-11-12
18   3895086          Bayer Leverkusen             FC Heidenheim  2023-09-24
19   3895309         Borussia Dortmund          Bayer Leverkusen  2024-04-21
20   3895258                   FC Köln          Bayer Leverkusen  2024-03-03
21   3895244             FC Heidenheim          Bayer Leverkusen  2024-02-17
22   3895232          Bayer Leverkusen             Bayern Munich  2024-02-10
23   3895210          Bayer Leverkusen  Borussia Mönchengladbach  2024-01-27
24   3895202                RB Leipzig          Bayer Leverkusen  2024-01-20
25   3895194                  Augsburg          Bayer Leverkusen  2024-01-13
26   3895182          Bayer Leverkusen                    Bochum  2023-12-20
27   3895167             VfB Stuttgart          Bayer Leverkusen  2023-12-10
28   3895153             Werder Bremen          Bayer Leverkusen  2023-11-25
29   3895113                 Wolfsburg          Bayer Leverkusen  2023-10-21
30   3895095              FSV Mainz 05          Bayer Leverkusen  2023-09-30
31   3895067          Bayer Leverkusen              Darmstadt 98  2023-09-02
32   3895060  Borussia Mönchengladbach          Bayer Leverkusen  2023-08-26
33   3895052          Bayer Leverkusen                RB Leipzig  2023-08-19

In [34]:
sb.competitions()

c:\Users\xaral\AppData\Local\Programs\Python\Python313\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-11-15T23:17:41.827093,2025-11-15T23:17:41.827093,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,NaN,NaN,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2026-05-12T21:18:08.827431,2026-05-02T02:07:18.902396,2026-05-02T02:07:18.902396,2026-05-12T21:18:08.827431
3,16,4,Europe,Champions League,male,False,False,2018/2019,2026-05-15T15:54:04.598614,2021-06-13T16:17:31.694,NaN,2026-05-15T15:54:04.598614
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,NaN,2024-02-13T02:35:28.134882
...,...,...,...,...,...,...,...,...,...,...,...,...
75,35,75,Europe,UEFA Europa League,male,False,False,1988/1989,2026-04-11T12:48:10.012987,2021-06-13T16:17:31.694,NaN,2026-04-11T12:48:10.012987
76,53,315,Europe,UEFA Women's Euro,female,False,True,2025,2026-04-27T22:02:42.690507,2026-04-27T22:03:28.087062,2026-04-27T22:03:28.087062,2026-04-27T22:02:42.690507
77,53,106,Europe,UEFA Women's Euro,female,False,True,2022,2026-05-05T03:03:04.199896,2026-05-05T03:05:32.480837,2026-05-05T03:05:32.480837,2026-05-05T03:03:04.199896
78,72,107,International,Women's World Cup,female,False,True,2023,2026-05-03T13:51:31.021141,2026-05-03T13:55:52.303219,2026-05-03T13:55:52.303219,2026-05-03T13:51:31.021141
79,72,30,International,Women's World Cup,female,False,True,2019,2026-05-15T15:31:40.299642,2021-06-13T16:17:31.694,NaN,2026-05-15T15:31:40.299642

In [35]:
df_pass.to_csv('week1_cleaned_passes.csv', index=False)